<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Aspire.Hosting.MongoDB" Version="13.1.2" />
		<PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.1.2" />
		<PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
		<PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
		<PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.3.0" />
		<PackageVersion Include="MongoDB.Driver" Version="3.7.0" />
		<PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
		<PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
		<PackageVersion Include="SideEffect.DataTransfer" Version="0.5.2" />
		<PackageVersion Include="SideEffect.Extensions" Version="0.5.2" />
		<PackageVersion Include="SideEffect.Files" Version="0.5.2" />
		<PackageVersion Include="SideEffect.Messaging" Version="0.5.2" />
		<PackageVersion Include="SideEffect.Messaging.RabbitMQ" Version="0.5.2" />
	</ItemGroup>
</Project>
